name: CD - Neptun-Stream
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Download repository code
            - uses: actions/checkout@v3
            # Deploy via SSH
            - uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    # Update package index and install dependencies
                    sudo dnf update -y
                    sudo dnf install -y git docker

                    # Verify installations
                    docker --version

                    # Install Docker Compose
                    sudo systemctl enable docker
                    sudo systemctl start docker

                    sudo usermod -aG docker ${{secrets.SSH_USERNAME}}

                    # Install Docker Compose
                    sudo mkdir -p /usr/local/lib/docker/cli-plugins
                    
                    sudo curl -SL https://github.com/docker/buildx/releases/download/v0.17.1/buildx-v0.17.1.linux-amd64 -o /usr/local/lib/docker/cli-plugins/docker-buildx

                    sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx

                    # Verify installations
                    docker buildx version

                    # Navigate to the project directory and deploy
                    cd /home/ec2-user/
                    if [! -d "neptun-stream"]; then
                        git clone https://github.com/aizhanmaksatbek/neptun-stream.git
                    fi
                    cd neptun-stream
                    git fetch origin main
                    git reset --hard origin/main
                    docker compose up -d --build