name: CD - Neptun-Stream
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Download repository code
            - uses: actions/checkout@v3
            # Deploy via SSH
            - uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    # Update package index and install dependencies
                    sudo dnf update -y
                    sudo dnf install git -y
                    sudo dnf install docker -y

                    # Verify installations
                    docker --version

                    # Install Docker Compose
                    sudo systemctl start docker
                    sudo systemctl enable docker

                    sudo mkdir -p /usr/local/lib/docker/cli-plugins
                    sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
                    -o /usr/local/lib/docker/cli-plugins/docker-compose
                    sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

                    # Verify installations
                    docker compose version

                    # Navigate to the project directory and deploy
                    cd /home/ec2-user/
                    git clone git@github.com:aizhanmaksatbek/neptun-stream.git
                    cd neptun-stream
                    git fetch origin main
                    git reset --hard origin/main
                    docker compose up -d --build